name: "Run JavaScript Action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm rebuild --target=8.1.0 --target_platform=linux --target_arch=x64 --target_libc=glibc --update-binary

    - uses: ./
      with:
        oauthToken: ${{ secrets.OAUTH_TOKEN }}
        folderId: ${{ secrets.FOLDER_ID }}
