name: "Run JavaScript Action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '7.2'
        registry-url: 'https://registry.npmjs.org'
    - uses: actions/checkout@v1

    - run: npm ci

    - uses: ./
      with:
        oauthToken: ${{ secrets.OAUTH_TOKEN }}
        folderId: ${{ secrets.FOLDER_ID }}
