name: "Run JavaScript Action"
on:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - uses: actions/checkout@v1

    - run: npm install

    - uses: ./
      with:
        oauthToken: ${{ secrets.OAUTH_TOKEN }}
        folderId: ${{ secrets.FOLDER_ID }}
