name: "Run JavaScript Action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm rebuild

    - uses: ./
      with:
        oauthToken: ${{ secrets.OAUTH_TOKEN }}
        folderId: ${{ secrets.FOLDER_ID }}
